# 生产环境核心服务配置 - 只包含业务服务

services:
  ljwx-mysql:
    ports: [] # 不暴露端口
    deploy:
      resources:
        limits: {memory: 2G, cpus: '1.0'}
        reservations: {memory: 1G, cpus: '0.5'}
    labels:
      - "com.ljwx.service=mysql"
      - "com.ljwx.backup=enabled"

  ljwx-redis:
    ports: [] # 不暴露端口
    deploy:
      resources:
        limits: {memory: 1G, cpus: '0.5'}
        reservations: {memory: 512M, cpus: '0.25'}
    labels:
      - "com.ljwx.service=redis"
      - "com.ljwx.backup=enabled"

  ljwx-boot:
    ports: ["${LJWX_BOOT_PORT:-9998}:9998"] # 只暴露业务端口
    deploy:
      resources:
        limits: {memory: 4G, cpus: '2.0'}
        reservations: {memory: 2G, cpus: '1.0'}
    labels:
      - "com.ljwx.service=ljwx-boot"
      - "traefik.enable=true"

  ljwx-bigscreen:
    deploy:
      resources:
        limits: {memory: 2G, cpus: '1.0'}
        reservations: {memory: 1G, cpus: '0.5'}
    labels:
      - "com.ljwx.service=ljwx-bigscreen"

  ljwx-admin:
    deploy:
      resources:
        limits: {memory: 512M, cpus: '0.5'}
        reservations: {memory: 256M, cpus: '0.25'}
    labels:
      - "com.ljwx.service=ljwx-admin" 